import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { OpenPanelComponent } from '@openpanel/nextjs';

import "./globals.css";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>{children}</body>
      {process.env.NODE_ENV === 'production' && (
        <OpenPanelComponent
        clientId="38367d47-a61c-41ba-82a5-66c9f909aaa0"
        trackScreenViews={true}
        trackAttributes={true}
        trackOutgoingLinks={true}
        // If you have a user id, you can pass it here to identify the user
        // profileId={'123'}
      />
      )}
    </html>
  );
}
